### PR TITLE
A few suggestions

### PR DESCRIPTION
**Pull request by Eldrinn-Elantey**
I offer a few suggestions for inclusion in the resource pack

### CODE REVIEW

**Comment by Ethryan** [comment]
Ok, i will look through these when I have time.

**Review by Ethryan — COMMENTED** [review]
Questions:
gt.metaitem.01/700 <- Why the color change?,
gt.metaitem.01/701-704 <- Too large, this pack is based on 32x32. i would rather keep it that way.
gt.metaitem.01/705-706 <- why change from the original?
gt.metaitem.01/710-720 <-  Too large, this pack is based on 32x32. i would rather keep it that way.
gt.metaitem.02/559 <- Much too large, and too far from the original texture.
gt.metaitem.02/560 <- Closer to the original, but still too large
gt.metaitem.02/561-564 <- Too large, and look a bit strange sadly.
gt.metaitem.02/565 <- No, one in this pack is better i think.
gt.metaitem.02/566-568 <- Too large, and look a bit strange sadly.
gt.metaitem.03/10 <- Too Large
gt.metaitem.03/11 <- Too large, too far from original
gt.metaitem.03/12-13 <- Why the change?
gt.metaitem.03/14 <- Too large, too far from original
gt.metaitem.03/15 <- Too large, too far from original
gt.metaitem.03/16 <- Too large, too far from original
gt.metaitem.03/18 <- Too large, too far from original
gt.metaitem.03/19 <- Too large
gt.metaitem.03/20 <- Too large, too far from original
assets/minecraft/textures/font/Thumbs.db <- remove this one
assets/minecraft/textures/font/ascii.png <- Ok
assets/minecraft/textures/font/ascii_fat.png <- Ok
assets/minecraft/textures/font/ascii_sga.png <- Ok
assets/railcraft/textures/blocks/fluids/creosote_flow.png <- Too large.
assets/railcraft/textures/blocks/fluids/creosote_still.png <- Too large.
assets/railcraft/textures/blocks/fluids/steam_still.png <- Looks good, but shrink it to 32x640.

**Comment by Eldrinn-Elantey** [comment]
Answers:

gt.metaitem.01/700 <- The original color merges with the interface
gt.metaitem.01/701-704 <- I understand myself that I agree that 32 looks better, but I want to note that the original textures of the objects are gregtech 16x16. There is also a single style and convenience in orientation
gt.metaitem.01/705-706 <- For a single style
gt.metaitem.01/710-720 <- I understand myself that I agree that 32 looks better, but I want to note that the original textures of the objects are gregtech 16x16. There is also a single style and convenience in orientation
gt.metaitem.02/559 <- Much too large, and too far from the original texture.
gt.metaitem.02/560 <- Closer to the original, but still too large
gt.metaitem.02/561-564 <- Too large, and look a bit strange sadly.
gt.metaitem.02/565 <- No, one in this pack is better i think.
gt.metaitem.02/566-568 <- Too large, and look a bit strange sadly.
gt.metaitem.03/10 <- You can take these textures as a basis and use algorithms to reduce them to a resolution of 32x32
gt.metaitem.03/11 <- You can take these textures as a basis and use algorithms to reduce them to a resolution of 32x32
gt.metaitem.03/12-13 <- I wasn't sure which texture is responsible for the vacuum tube. Now I see that this is completely something else. I can't even figure out what exactly it is
gt.metaitem.03/14 <- You can take these textures as a basis and use algorithms to reduce them to a resolution of 32x32
gt.metaitem.03/15 <- You can take these textures as a basis and use algorithms to reduce them to a resolution of 32x32
gt.metaitem.03/16 <- You can take these textures as a basis and use algorithms to reduce them to a resolution of 32x32
gt.metaitem.03/18 <- You can take these textures as a basis and use algorithms to reduce them to a resolution of 32x32
gt.metaitem.03/19 <- You can take these textures as a basis and use algorithms to reduce them to a resolution of 32x32
gt.metaitem.03/20 <- You can take these textures as a basis and use algorithms to reduce them to a resolution of 32x32
assets/railcraft/textures/blocks/fluids/steam_still.png <- I'll try to do something

**Comment by Eldrinn-Elantey** [comment]
steam_still

**Pull request merged**
